# help.vim can be used to make it easier to populate this list (for vim)
# vsplit this file and errors.txt
# (load help.json into Plover)


plover_briefs={
"EFRG", # !! (EFRG,): everything -- ['ɛvɹiθɪŋ']
"POPB", # !! (PON,): upon -- ['əpɑn']
"PHAPBLGD", # !! (MAJD,): imagined -- ['ɪmædʒənd']
"TPHAO*EUGT", # !! (NII*GT,): knight -- ['naɪt']
"PWRAEG", # !! (BRAEG,): breaking -- ['bɹeɪkɪŋ']
"PWRAEBG/-G", # !! (BRAEK, -G): breaking -- ['bɹeɪkɪŋ']
"PUPBD", # !! (PUND,): punished -- ['pənɪʃt']
"P-RBD", # !! (P-ʃD,): punished -- ['pənɪʃt']
"P-RB/-D", # !! (P-ʃ, -D): punished -- ['pənɪʃt']
"PUR/-D", # !! (PUR, -D): purchased -- ['pəɹtʃəst']
"PUFPD", # !! (PUChD,): purchased -- ['pəɹtʃəst']
"PR-FPD", # !! (PR-ChD,): purchased -- ['pəɹtʃəst']
"PR-FP/-D", # !! (PR-Ch, -D): purchased -- ['pəɹtʃəst']
"EFRPB", # !! (ERch,): everyone -- ['ɛvɹiwən']
"*EFRPB", # !! (E*Rch,): everyone -- ['ɛvɹiwən']
"PHRARS", # !! (PLARS,): particulars -- ['pəɹtɪkjəɫəɹz']
"TOED", # !! (TOED,): today -- ['tədeɪ', 'tudeɪ']
"SRAOEPBT", # !! (VEENT,): convenient -- ['kənvinjənt']
"SRAOEPB", # !! (VEEN,): convenient -- ['kənvinjənt']
"SROLS", # !! (VOLS,): volumes -- ['vɑɫjumz']
"SROL/-S", # !! (VOL, -S): volumes -- ['vɑɫjumz']
"A/K-P", # !! (A, K-P): accompany -- ['əkəmpəni']
"TPH*PB", # !! (N*N,): inn -- ['ɪn']
"R*EUBGS", # !! (RI*KS,): ridiculous -- ['ɹɪdɪkjəɫəs']
"PROEUPT", # !! (PROIPT,): proprietary -- ['pɹəpɹaɪətɛɹi']
"PRAFS", # !! (PRAFS,): paragraphs -- ['pæɹəɡɹæfs', 'pɛɹəɡɹæfs']
"TH-R/PWAOEU", # !! (TH-R, BII): thereby -- ['ðɛɹbaɪ']
"THR/PW*EU", # !! (TL, BI*): thereby -- ['ðɛɹbaɪ']
"THR-B", # !! (TL-B,): thereby -- ['ðɛɹbaɪ']
"THR*RB", # !! (TL*ʃ,): thereby -- ['ðɛɹbaɪ']
"HAPS", # !! (HAPS,): happens -- ['hæpənz']
"WEPS", # !! (WEPS,): weapons -- ['wɛpənz']
"TPHAOURB/A*L", # !! (NUUʃ, A*L): unusual -- ['ənjuʒuəɫ', 'ənjuʒwəɫ']
"TPHAOURB", # !! (NUUʃ,): unusual -- ['ənjuʒuəɫ', 'ənjuʒwəɫ']
"K-TS", # !! (K-TS,): accounts -- ['əkaʊnts']
"PW-GS", # !! (B-ʃn,): beings -- ['biɪŋz']
"-BGZ", # !! (-KZ,): beings -- ['biɪŋz']
"HUPBS", # !! (HUNS,): hundreds -- ['həndəɹdz', 'həndɹədz', 'hənəɹdz']
"HOEUPBS", # !! (HOINS,): hundreds -- ['həndəɹdz', 'həndɹədz', 'hənəɹdz']
"SPHA*EUPB", # !! (SMAI*N,): mistaken -- ['mɪsteɪkən']
"TPOFR", # !! (FOFR,): forever -- ['fəɹɛvəɹ']
"TPR-FR", # !! (FR-FR,): forever -- ['fəɹɛvəɹ']
"TPR*FR", # !! (FR*FR,): forever -- ['fəɹɛvəɹ']
"SUGS", # !! (SUʃn,): suggestion -- ['sədʒɛstʃən']
"HOEUR", # !! (HOIR,): hero -- ['hiɹoʊ', 'hɪɹoʊ']
"HO*EUR", # !! (HOI*R,): hero -- ['hiɹoʊ', 'hɪɹoʊ']
"WAFS", # !! (WAFS,): waves -- ['weɪvz']
"WAF/-S", # !! (WAF, -S): waves -- ['weɪvz']
"RA*EUPBG", # !! (RAI*NG,): reign -- ['ɹeɪn']
"AO*ELG", # !! (EE*LG,): emotion -- ['imoʊʃən', 'ɪmoʊʃən']
"AO*EGS", # !! (EE*ʃn,): emotion -- ['imoʊʃən', 'ɪmoʊʃən']
"TKPW-PBS", # !! (G-NS,): guns -- ['ɡənz']
"WHAOEULS", # !! (WHIILS,): whilst -- ['waɪɫst']
"KPRORD", # !! (XRORD,): extraordinary -- ['ɛkstɹəɔɹdənɛɹi', 'ɪkstɹɔɹdənɛɹi']
"KPRAORD", # !! (XRAORD,): extraordinary -- ['ɛkstɹəɔɹdənɛɹi', 'ɪkstɹɔɹdənɛɹi']
"KPAORD", # !! (XAORD,): extraordinary -- ['ɛkstɹəɔɹdənɛɹi', 'ɪkstɹɔɹdənɛɹi']
"TPOLS", # !! (FOLS,): follows -- ['fɑɫoʊz']
"KROEURD", # !! (KROIRD,): occurred -- ['əkəɹd']
"POEUPBD", # !! (POIND,): appointed -- ['əpɔɪntɪd']
"SRAPBS/-D", # !! (VANS, -D): advanced -- ['ədvænst']
"PREUPBZ", # !! (PRINZ,): principles -- ['pɹɪnsəpəɫz']
"PREUPB", # !! (PRIN,): principle -- ['pɹɪnsəpəɫ']
"TUPBG", # !! (TUNG,): tongue -- ['təŋ']
"O*ERZ", # !! (OE*RZ,): otherwise -- ['əðəɹwaɪz']
"AOEPBTS", # !! (EENTS,): events -- ['ivɛnts', 'ɪvɛnts']
"*EFD", # !! (E*FD,): evidence -- ['ɛvədəns']
"KAPT", # !! (KAPT,): captain -- ['kæptən']
"TPHORT", # !! (NORT,): north -- ['nɔɹθ']
"*URPBD", # !! (U*RND,): understood -- ['əndəɹstʊd']
"URBL", # !! (UʃL,): usual -- ['juʒəwəɫ', 'juʒuəɫ']
"A*FRDZ", # !! (A*FRDZ,): afterwards -- ['æftəɹwəɹdz']
"SAF", # !! (SAF,): save -- ['seɪv']
"SERPBL", # !! (SERNL,): certainly -- ['səɹtənɫi']
"PREUT", # !! (PRIT,): pretty -- ['pɹɪti']
"HUPBD", # !! (HUND,): hundred -- ['həndəɹd', 'həndɹəd', 'həndɹɪd', 'hənəɹd']
"HOEUPB", # !! (HOIN,): hundred -- ['həndəɹd', 'həndɹəd', 'həndɹɪd', 'hənəɹd']
"TPHU", # !! (NU,): new -- ['nju', 'nu']
"AULS", # !! (AULS,): always -- ['ɔɫweɪz', 'ɔɫwiz']
"TPHAE", # !! (NAE,): anyway -- ['ˈɛniˌweɪ']
"PRAOERBT", # !! (PREEʃT,): appreciate -- ['əˈpɹiʃiˌeɪt']
"PRAOERB/KWRAEUT", # !! (PREEʃ, YAIT): appreciate -- ['əˈpɹiʃiˌeɪt']
"PRAOERB", # !! (PREEʃ,): appreciate -- ['əˈpɹiʃiˌeɪt']
"SOERBGS", # !! (SOERKS,): association -- ['əˌsoʊsiˈeɪʃən', 'əˌsoʊʃiˈeɪʃən']
"SOEGS", # !! (SOEʃn,): association -- ['əˌsoʊsiˈeɪʃən', 'əˌsoʊʃiˈeɪʃən']
"R-PBG", # !! (R-NG,): reasoning -- ['ˈɹizənɪŋ']
"R-PB/-G", # !! (R-N, -G): reasoning -- ['ˈɹizənɪŋ']
"PW-FR/HAPBD", # !! (B-FR, HAND): beforehand -- ['bɪˈfɔɹˌhænd']
"PW*F/HAPBD", # !! (B*F, HAND): beforehand -- ['bɪˈfɔɹˌhænd']
"PW*F/HA*PBD", # !! (B*F, HA*ND): beforehand -- ['bɪˈfɔɹˌhænd']
"PROET", # !! (PROET,): appropriate -- ['əˈpɹoʊpɹiˌeɪt', 'əˈpɹoʊpɹiət']
"PROEPT", # !! (PROEPT,): appropriate -- ['əˈpɹoʊpɹiˌeɪt', 'əˈpɹoʊpɹiət']
"PHREURB", # !! (PLIʃ,): accomplish -- ['əˈkɑmpɫɪʃ']
"UPB/TPHES", # !! (UN, NES): unnecessary -- ['ənˈnɛsəˌsɛɹi']
"SWAEUL", # !! (SWAIL,): sexually -- ['ˈsɛkʃuəɫi']
"SWAUL/TEU", # !! (SWAUL, TI): sexuality -- ['ˌsɛkʃuˈæɫəti']
"SWALT", # !! (SWALT,): sexuality -- ['ˌsɛkʃuˈæɫəti']
"SWEPB", # !! (SWEN,): sewn -- ['ˈsoʊn']
"SWE", # !! (SWE,): sew -- ['ˈsoʊ']
"SWEPBG", # !! (SWENG,): sewing -- ['ˈsoʊɪŋ']
"SWEG", # !! (SWEG,): sewing -- ['ˈsoʊɪŋ']
"SWE/-G", # !! (SWE, -G): sewing -- ['ˈsoʊɪŋ']
"SWAUL", # !! (SWAUL,): sexual -- ['ˈsɛkʃuəɫ']
"S-B", # !! (S-B,): somebody -- ['ˈsəmˌbɑdi', 'ˈsəmbəˌdi']
"SPH-B", # !! (SM-B,): somebody -- ['ˈsəmˌbɑdi', 'ˈsəmbəˌdi']
"HR-PLTS", # !! (L-MTS,): elements -- ['ˈɛɫəmənts']
"PREZ", # !! (PREZ,): president -- ['ˈpɹɛzəˌdɛnt', 'ˈpɹɛzɪdənt']
"KWRA*ER", # !! (YAE*R,): area -- ['ˈɛɹiə']
"SWR", # !! (SWR,): somewhere -- ['ˈsəmˌwɛɹ']
"SW-R", # !! (SW-R,): somewhere -- ['ˈsəmˌwɛɹ']
"SPW-R", # !! (SB-R,): somewhere -- ['ˈsəmˌwɛɹ']
"SPH/WR", # !! (SM, WR): somewhere -- ['ˈsəmˌwɛɹ']
"OEB", # !! (OEB,): observe -- ['əbˈzəɹv']
"PW-PB", # !! (B-N,): been -- ['ˈbɪn', 'bən', 'bɪn']
"SPOPBS/-BLT", # !! (SPONS, -BLT): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"SPOPBLT", # !! (SPONLT,): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"SPOPBLGT", # !! (SPOJT,): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"SPOPBGT", # !! (SPONGT,): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"SPOPB/EUBLT", # !! (SPON, IBLT): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"SPOBLT", # !! (SPOBLT,): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"SPOPBT", # !! (SPONT,): responsibility -- ['ɹiˌspɑnsəˈbɪɫəti']
"REPT", # !! (REPT,): represent -- ['ˌɹɛpɹɪˈzɛnt']
"W-R/*EUPB", # !! (W-R, I*N): wherein -- ['hwɛˈɹɪn', 'wɛˈɹɪn']
"WR-PB", # !! (WR-N,): wherein -- ['hwɛˈɹɪn', 'wɛˈɹɪn']
"TPHAOUP", # !! (NUUP,): newspaper -- ['ˈnuzˌpeɪpəɹ']
"WR-FR", # !! (WR-FR,): wherever -- ['hwɛˈɹɛvəɹ', 'wɛˈɹɛvəɹ']
"WHR-FR", # !! (WL-FR,): wherever -- ['hwɛˈɹɛvəɹ', 'wɛˈɹɛvəɹ']
"W-R/-FR", # !! (W-R, -FR): wherever -- ['hwɛˈɹɛvəɹ', 'wɛˈɹɛvəɹ']
"W-FR", # !! (W-FR,): wherever -- ['hwɛˈɹɛvəɹ', 'wɛˈɹɛvəɹ']
"P-FRGS", # !! (P-FRʃn,): perfection -- ['pəɹˈfɛkʃən']
"WRELS", # !! (WRELS,): elsewhere -- ['ˈɛɫˌswɛɹ']
"ELS/W-R", # !! (ELS, W-R): elsewhere -- ['ˈɛɫˌswɛɹ']
"T-PB/WAEL", # !! (T-N, WAEL): continually -- ['kənˈtɪnjuəɫi', 'kənˈtɪnjuɫi']
"T-PB/HREU", # !! (T-N, LI): continually -- ['kənˈtɪnjuəɫi', 'kənˈtɪnjuɫi']
"THROF", # !! (TLOF,): thereof -- ['ˌðɛˈɹəv']
"THR/*F", # !! (TL, *F): thereof -- ['ˌðɛˈɹəv']
"S-BGS", # !! (S-KS,): sex -- ['ˈsɛks']
"HROEL", # !! (LOEL,): local -- ['ˈɫoʊkəɫ']
"TKPW-PB", # !! (G-N,): gun -- ['ˈɡən']
"TPHEUB", # !! (NIB,): anybody -- ['ˈɛnibədi']
"*UPBG", # !! (U*NG,): uncle -- ['ˈəŋkəɫ']
"PHAOED", # !! (MEED,): immediate -- ['ˌɪˈmiˌdiət']
"RERD", # !! (RERD,): remembered -- ['ɹiˈmɛmbəɹd', 'ɹɪˈmɛmbəɹd']
"RER/-D", # !! (RER, -D): remembered -- ['ɹiˈmɛmbəɹd', 'ɹɪˈmɛmbəɹd']
"TKPWEPBS", # !! (GENS,): against -- ['əˈɡeɪnst', 'əˈɡɛnst']
"TKPW*EPBS", # !! (GE*NS,): against -- ['əˈɡeɪnst', 'əˈɡɛnst']
"TPHEUR", # !! (NIR,): anywhere -- ['ˈɛniˌwɛɹ', 'ˈɛnihˌwɛɹ']
"TPHEU/WR*", # !! (NI, WR*): anywhere -- ['ˈɛniˌwɛɹ', 'ˈɛnihˌwɛɹ']
"TPHAOEUR", # !! (NIIR,): anywhere -- ['ˈɛniˌwɛɹ', 'ˈɛnihˌwɛɹ']
"RERL", # !! (RERL,): earlier -- ['ˈəɹɫiəɹ']
"SERPB", # !! (SERN,): certain -- ['ˈsɝtən']
"HOUFR", # !! (HOUFR,): however -- ['ˌhaʊˈɛvɝ']
"HOUF", # !! (HOUF,): however -- ['ˌhaʊˈɛvɝ']
"TPHUF", # !! (NUF,): enough -- ['iˈnəf', 'ɪˈnəf']
"OERS", # !! (OERS,): others -- ['ˈəðɝz']
"OER/-S", # !! (OER, -S): others -- ['ˈəðɝz']
"SKRETD", # (SKRETD,): credit -- ['ˈkɹɛdət', 'ˈkɹɛdɪt']
"KREUTD", # (KRITD,): credit -- ['ˈkɹɛdət', 'ˈkɹɛdɪt']
"KRETD", # (KRETD,): credit -- ['ˈkɹɛdət', 'ˈkɹɛdɪt']
"KRET", # (KRET,): credit -- ['ˈkɹɛdət', 'ˈkɹɛdɪt']
"KROL", # (KROL,): control -- ['kənˈtɹoʊɫ']
"SREUBL", # (VIBL,): visible -- ['ˈvɪzəbəɫ']
"SELD", # (SELD,): seldom -- ['ˈsɛɫdəm']
"HR-PBS", # (L-NS,): license -- ['ˈɫaɪsəns']
"HR-PB", # (L-N,): license -- ['ˈɫaɪsəns']
"KREU", # (KRI,): country -- ['ˈkəntɹi']
"TKPW/-G", # (G, -G): going -- ['ˈɡoʊɪn', 'ˈɡoʊɪŋ']
"TKPW-G", # (G-G,): going -- ['ˈɡoʊɪn', 'ˈɡoʊɪŋ']
"SK-D", # (SK-D,): asked -- ['ˈæskt', 'ˈæst']
"-T", # (-T,): the -- ['ˈðə', 'ðə', 'ði']
"PEFGS", # (PEFʃn,): possession -- ['pəˈzɛʃən']
"P*EGS", # (PE*ʃn,): possession -- ['pəˈzɛʃən']
"TKWEUD/A*L", # (DWID, A*L): individual -- ['ˌɪndəˈvɪdʒəwəɫ']
"TKWAL", # (DWAL,): individual -- ['ˌɪndəˈvɪdʒəwəɫ']
"SREUPBLG", # (VIJ,): individual -- ['ˌɪndəˈvɪdʒəwəɫ']
"SREUD", # (VID,): individual -- ['ˌɪndəˈvɪdʒəwəɫ']
"SR*EUD", # (VI*D,): individual -- ['ˌɪndəˈvɪdʒəwəɫ']
"SKES", # (SKES,): success -- ['səkˈsɛs']
"WRO", # (WRO,): wrote -- ['ˈɹoʊt']
"HOEUF", # (HOIF,): heavy -- ['ˈhɛvi']
"TPOL", # (FOL,): follow -- ['ˈfɑɫoʊ']
"THEUG", # (THIG,): thinking -- ['ˈθɪŋkɪŋ']
"THEU/-G", # (THI, -G): thinking -- ['ˈθɪŋkɪŋ']
"KORG", # (KORG,): according -- ['əˈkɔɹdɪŋ']
"TPO*EUL", # (FOI*L,): fellow -- ['ˈfɛɫoʊ']
"TP*EL", # (FE*L,): fellow -- ['ˈfɛɫoʊ']
"HEUFRT", # (HIFRT,): history -- ['ˈhɪstɝi', 'ˈhɪstɹi']
"OEPD", # (OEPD,): opened -- ['ˈoʊpənd']
"OEP/-D", # (OEP, -D): opened -- ['ˈoʊpənd']
"PWHRO", # (BLO,): below -- ['biˈɫoʊ', 'bɪˈɫoʊ']
"S*FS", # (S*FS,): service -- ['ˈsɝvəs', 'ˈsɝvɪs']
"TPEBG", # (FEK,): effect -- ['ˈifɛkt', 'əˈfɛkt', 'ɪˈfɛkt']
"SULD", # (SULD,): suddenly -- ['ˈsədənɫi']
"SUD/HREU", # (SUD, LI): suddenly -- ['ˈsədənɫi']
"PHUPB", # (MUN,): money -- ['ˈməni']
"TK*T", # (D*T,): death -- ['ˈdɛθ']
"TKPWAPB", # (GAN,): began -- ['biˈɡæn', 'bɪˈɡæn']
"STKPWAPB", # (SGAN,): began -- ['biˈɡæn', 'bɪˈɡæn']
"TWAOEPB", # (TWEEN,): between -- ['bitˈwin', 'bɪtˈwin']
"PWAU", # (BAU,): because -- ['bɪˈkɑz', 'bɪˈkəz', 'bɪˈkɔz', 'bɪkəz']
"TKR-BT/-G", # (DR-BT, -G): distributing -- ['dɪˈstɹɪbjutɪŋ']
"RULTS", # (RULTS,): results -- ['ɹiˈzəɫts', 'ɹɪˈzəɫts']
"RULT/-S", # (RULT, -S): results -- ['ɹiˈzəɫts', 'ɹɪˈzəɫts']
"EFRB", # (EFRB,): everybody -- ['ˈɛvɹiˌbɑdi']
"SAOEFD", # (SEEFD,): received -- ['ɹəˈsivd', 'ɹiˈsivd', 'ɹɪˈsivd']
"SAO*EFD", # (SEE*FD,): received -- ['ɹəˈsivd', 'ɹiˈsivd', 'ɹɪˈsivd']
"SPH/WHA", # (SM, WHA): somewhat -- ['ˈsəmˈwət', 'ˈsəmhˈwət']
"SWHA", # (SWHA,): somewhat -- ['ˈsəmˈwət', 'ˈsəmhˈwət']
"OUDZ", # (OUDZ,): outside -- ['ˈaʊtˈsaɪd']
"PHAOELD", # (MEELD,): immediately -- ['ˌɪˈmiˌdiətɫi']
"PHAOED/HREU", # (MEED, LI): immediately -- ['ˌɪˈmiˌdiətɫi']
"PHAO*ELD", # (MEE*LD,): immediately -- ['ˌɪˈmiˌdiətɫi']
"POGS", # (POʃn,): position -- ['pəˈzɪʃən']
"PWAEUPL", # (BAIM,): became -- ['biˈkeɪm', 'bɪˈkeɪm']
"TPHOEBD", # (NOEBD,): nobody -- ['ˈnoʊˌbɑˌdi', 'ˈnoʊbədi']
"TPHOEB", # (NOEB,): nobody -- ['ˈnoʊˌbɑˌdi', 'ˈnoʊbədi']
"SPHAEUBG", # (SMAIK,): mistake -- ['mɪˈsteɪk']
"SPHA*EUFBG", # (SMAI*FK,): mistake -- ['mɪˈsteɪk']
"SPHA*EUBG", # (SMAI*K,): mistake -- ['mɪˈsteɪk']
"KEBGTD", # (KEKTD,): connected -- ['kəˈnɛktɪd']
"KEBGD/-D", # (KEKD, -D): connected -- ['kəˈnɛktɪd']
"KEBG/-D", # (KEK, -D): connected -- ['kəˈnɛktɪd']
"R*ELGS", # (RE*Lʃn,): relation -- ['ɹiˈɫeɪʃən']
"PWAERPBG", # (BAERNG,): bearing -- ['ˈbɛɹɪŋ']
"PWAERG", # (BAERG,): bearing -- ['ˈbɛɹɪŋ']
"PWAER/-G", # (BAER, -G): bearing -- ['ˈbɛɹɪŋ']
"URPBGD", # (URNGD,): understanding -- ['ˌəndɝˈstændɪŋ']
"URPBD/-G", # (URND, -G): understanding -- ['ˌəndɝˈstændɪŋ']
"URBGD", # (URKD,): understanding -- ['ˌəndɝˈstændɪŋ']
"STPA*BGS", # (SFA*KS,): satisfaction -- ['ˌsætəsˈfækʃən', 'ˌsætɪsˈfækʃən']
"PRAEP", # (PRAEP,): prepare -- ['pɹiˈpɛɹ']
"PRAO*EP", # (PREE*P,): prepare -- ['pɹiˈpɛɹ']
"PRAOEP", # (PREEP,): prepare -- ['pɹiˈpɛɹ']
"TPHUPLS", # (NUMS,): numbers -- ['ˈnəmbɝz']
"TR-D", # (TR-D,): interested -- ['ˈɪntɝəstəd', 'ˈɪntɝɪstɪd', 'ˈɪntɹəstɪd', 'ˈɪntɹɪstɪd']
"WHR*", # (WL*,): weather -- ['ˈwɛðɝ']
"TPHEUPB", # (NIN,): anyone -- ['ˈɛniˌwən', 'ˈɛniwən']
"TPHEU/W*UPB", # (NI, WU*N): anyone -- ['ˈɛniˌwən', 'ˈɛniwən']
"RORT", # (RORT,): report -- ['ɹiˈpɔɹt', 'ɹɪˈpɔɹt']
"RORPT", # (RORPT,): report -- ['ɹiˈpɔɹt', 'ɹɪˈpɔɹt']
"RORP", # (RORP,): report -- ['ɹiˈpɔɹt', 'ɹɪˈpɔɹt']
"ORP", # (ORP,): report -- ['ɹiˈpɔɹt', 'ɹɪˈpɔɹt']
"SOES/-D", # (SOES, -D): associated -- ['əˈsoʊsiˌeɪtɪd', 'əˈsoʊʃiˌeɪtɪd']
"WHAFR", # (WHAFR,): whatever -- ['ˌhwəˈtɛvɝ', 'ˌwəˈtɛvɝ']
"SRAPBG", # (VANG,): advantage -- ['ædˈvæntɪdʒ']
"SOET/-D", # (SOET, -D): associated -- ['əˈsoʊsiˌeɪtɪd', 'əˈsoʊʃiˌeɪtɪd']
"SOERBTD", # (SOEʃTD,): associated -- ['əˈsoʊsiˌeɪtɪd', 'əˈsoʊʃiˌeɪtɪd']
"SOERBT/-D", # (SOEʃT, -D): associated -- ['əˈsoʊsiˌeɪtɪd', 'əˈsoʊʃiˌeɪtɪd']
"SOERBD", # (SOEʃD,): associated -- ['əˈsoʊsiˌeɪtɪd', 'əˈsoʊʃiˌeɪtɪd']
"TPAEFT", # (FAEFT,): fifty -- ['ˈfɪfti']
"KO*EPS", # (KOE*PS,): copies -- ['ˈkɑpiz']
"TPEUS", # (FIS,): physical -- ['ˈfɪzɪkəɫ']
"PHAO*EPL", # (MEE*M,): medium -- ['ˈmidiəm']
"PRAOEPD", # (PREEPD,): prepared -- ['pɹiˈpɛɹd']
"PRAOEP/-D", # (PREEP, -D): prepared -- ['pɹiˈpɛɹd']
"PRAO*EPD", # (PREE*PD,): prepared -- ['pɹiˈpɛɹd']
"HRAPBLG", # (LAJ,): language -- ['ˈɫæŋɡwədʒ', 'ˈɫæŋɡwɪdʒ']
"AOEPBG", # (EENG,): evening -- ['ˈivnɪŋ']
"AOEPB/-G", # (EEN, -G): evening -- ['ˈivnɪŋ']
"TPAEPL", # (FAEM,): family -- ['ˈfæməɫi', 'ˈfæmɫi']
"THOUD", # (THOUD,): thousand -- ['ˈθaʊzən', 'ˈθaʊzənd']
"HEUPBD", # (HIND,): behind -- ['bɪˈhaɪnd']
"RURPB", # (RURN,): return -- ['ɹiˈtɝn', 'ɹɪˈtɝn']
"TOGT", # (TOGT,): together -- ['təˈɡɛðɝ']
"W-PB", # (W-N,): within -- ['wɪˈðɪn', 'wɪˈθɪn']
"-FR", # (-FR,): ever -- ['ˈɛvɝ']
"TPHO*ER", # (NOE*R,): another -- ['əˈnəðɝ']
"TPHOER", # (NOER,): another -- ['əˈnəðɝ']
"WOPL", # (WOM,): woman -- ['ˈwʊmən']
"TPHOG", # (NOG,): nothing -- ['ˈnəθɪŋ']
"PHAEPB", # (MAEN,): many -- ['ˈmɛni']
"AOEPB", # (EEN,): even -- ['ˈivɪn']
"THEU", # (THI,): think -- ['ˈθɪŋk']
"EFR", # (EFR,): every -- ['ˈɛvɝi', 'ˈɛvɹi']
"EF", # (EF,): every -- ['ˈɛvɝi', 'ˈɛvɹi']
"THRU", # (TLU,): through -- ['ˈθɹu']
"TKPW", # (G,): go -- ['ˈɡoʊ']
"WOUT", # (WOUT,): without -- ['wɪˈðaʊt', 'wɪˈθaʊt']
"WO*UT", # (WOU*T,): without -- ['wɪˈðaʊt', 'wɪˈθaʊt']
"WAOUT", # (WUUT,): without -- ['wɪˈðaʊt', 'wɪˈθaʊt']
"W/OUT", # (W, OUT): without -- ['wɪˈðaʊt', 'wɪˈθaʊt']
"RURPBG", # (RURNG,): returning -- ['ɹiˈtɝnɪŋ', 'ɹɪˈtɝnɪŋ']
"REPTD", # (REPTD,): represented -- ['ˌɹɛpɹɪˈzɛntɪd']
"REPD", # (REPD,): represented -- ['ˌɹɛpɹɪˈzɛntɪd']
"TPH-PBT", # (N-NT,): innocent -- ['ˈɪnəsənt']
"REFD", # (REFD,): recognized -- ['ˈɹɛkəɡˌnaɪzd']
"KUZ", # (KUZ,): cousin -- ['ˈkəzən']
"SROL", # (VOL,): volume -- ['ˈvɑɫjum']
"*EF/REU/WR", # (E*F, RI, WR): everywhere -- ['ˈɛvɹiˌwɛɹ', 'ˈɛvɹihˌwɛɹ']
"*EFR/WR", # (E*FR, WR): everywhere -- ['ˈɛvɹiˌwɛɹ', 'ˈɛvɹihˌwɛɹ']
"EF/REU/WR", # (EF, RI, WR): everywhere -- ['ˈɛvɹiˌwɛɹ', 'ˈɛvɹihˌwɛɹ']
"EFR/WR", # (EFR, WR): everywhere -- ['ˈɛvɹiˌwɛɹ', 'ˈɛvɹihˌwɛɹ']
"EFR/W-R", # (EFR, W-R): everywhere -- ['ˈɛvɹiˌwɛɹ', 'ˈɛvɹihˌwɛɹ']
"WEFR", # (WEFR,): everywhere -- ['ˈɛvɹiˌwɛɹ', 'ˈɛvɹihˌwɛɹ']
"PREUZ", # (PRIZ,): prison -- ['ˈpɹɪzən']
"TKWOPLT", # (DWOMT,): development -- ['dɪˈvɛɫəpmənt']
"SREPLT", # (VEMT,): development -- ['dɪˈvɛɫəpmənt']
"SREL/*PLT", # (VEL, *MT): development -- ['dɪˈvɛɫəpmənt']
"PW-BG/-G", # (B-K, -G): becoming -- ['bɪˈkəmɪŋ']
"TROUD", # (TROUD,): introduced -- ['ˌɪntɹəˈdust', 'ˌɪntɹoʊˈdust']
"TRO*UD", # (TROU*D,): introduced -- ['ˌɪntɹəˈdust', 'ˌɪntɹoʊˈdust']
"SK/-G", # (SK, -G): asking -- ['ˈæskɪŋ']
"SK-G", # (SK-G,): asking -- ['ˈæskɪŋ']
"STEUS", # (STIS,): cities -- ['ˈsɪtiz']
"STEU/-S", # (STI, -S): cities -- ['ˈsɪtiz']
"TKEG/-S", # (DEG, -S): degrees -- ['dɪˈɡɹiz']
"TK*EGS", # (DE*ʃn,): degrees -- ['dɪˈɡɹiz']
"PWREU/-G", # (BRI, -G): bringing -- ['ˈbɹɪŋɪŋ']
"PWREUG", # (BRIG,): bringing -- ['ˈbɹɪŋɪŋ']
"AEFT", # (AEFT,): evident -- ['ˈɛvədənt']
"*EFT", # (E*FT,): evident -- ['ˈɛvədənt']
"WHEFR", # (WHEFR,): whenever -- ['hwɛˈnɛvɝ', 'wɛˈnɛvɝ']
"WH-FR", # (WH-FR,): whenever -- ['hwɛˈnɛvɝ', 'wɛˈnɛvɝ']
"WH*FR", # (WH*FR,): whenever -- ['hwɛˈnɛvɝ', 'wɛˈnɛvɝ']
"RAOEUR", # (RIIR,): require -- ['ˌɹiˈkwaɪɝ', 'ɹiˈkwaɪɹ', 'ɹɪˈkwaɪɝ']
"TKEGS", # (DEʃn,): degrees -- ['dɪˈɡɹiz']
"AGS", # (Aʃn,): addition -- ['əˈdɪʃən']
"TPHOEUPBLG", # (NOIJ,): enjoy -- ['ˌɛnˈdʒɔɪ', 'ɪnˈdʒɔɪ']
"KAEUFL", # (KAIFL,): careful -- ['ˈkɛɹfəɫ']
"THEUS", # (THIS,): thinks -- ['ˈθɪŋks']
"KOEURBG", # (KOIʃG,): circle -- ['ˈsɝkəɫ']
"SOEURBG", # (SOIʃG,): circle -- ['ˈsɝkəɫ']
"SUFL", # (SUFL,): sufficiently -- ['səˈfɪʃəntɫi']
"SUF/HREU", # (SUF, LI): sufficiently -- ['səˈfɪʃəntɫi']
"PARD", # (PARD,): pardon -- ['ˈpɑɹdən']
"KEBGS", # (KEKS,): connection -- ['kəˈnɛkʃən']
"EFPBT", # (EFNT,): event -- ['iˈvɛnt', 'ɪˈvɛnt']
"AOEFPBT", # (EEFNT,): event -- ['iˈvɛnt', 'ɪˈvɛnt']
"AOEPBT", # (EENT,): event -- ['iˈvɛnt', 'ɪˈvɛnt']
"SR-PB", # (V-N,): haven't -- ['ˈhævən', 'ˈhævənt']
"HRAEUB", # (LAIB,): labor -- ['ˈɫeɪbɝ']
"PHEPL", # (MEM,): member -- ['ˈmɛmbɝ']
"PHEB", # (MEB,): member -- ['ˈmɛmbɝ']
"SEURL", # (SIRL,): circle -- ['ˈsɝkəɫ']
"SKHR", # (SChR,): circle -- ['ˈsɝkəɫ']
"KPERZ", # (XERZ,): exercise -- ['ˈɛksɝˌsaɪz']
"AOUFL", # (UUFL,): useful -- ['ˈjusfəɫ']
"PROEUS", # (PROIS,): process -- ['ˈpɹɑˌsɛs', 'ˈpɹɔˌsɛs']
"KHRUD", # (ChRUD,): included -- ['ˌɪnˈkɫudəd', 'ˌɪnˈkɫudɪd']
"PHEPBLG", # (MEJ,): message -- ['ˈmɛsədʒ', 'ˈmɛsɪdʒ']
"STKOFR", # (SDOFR,): discover -- ['dɪˈskəvɝ']
"SKOFR", # (SKOFR,): discover -- ['dɪˈskəvɝ']
"KUPBTSZ", # (KUNTSZ,): countries -- ['ˈkəntɹiz']
"KUPBTS", # (KUNTS,): countries -- ['ˈkəntɹiz']
"PHAPBLG", # (MAJ,): imagine -- ['ˌɪˈmædʒən']
"SREUS", # (VIS,): advice -- ['ædˈvaɪs', 'ədˈvaɪs']
"P*UG", # (PU*G,): putting -- ['ˈpətɪŋ', 'ˈpʊtɪŋ']
"TR-S", # (TR-S,): interests -- ['ˈɪntɝəsts', 'ˈɪntɝɪsts', 'ˈɪntɹəsts', 'ˈɪntɹɪsts']
"TPHAOETD", # (NEETD,): needed -- ['ˈnidəd', 'ˈnidɪd']
"WAUG", # (WAUG,): walking -- ['ˈwɔkɪŋ']
"TAEF", # (TAEF,): active -- ['ˈæktɪv']
"A*UG", # (AU*G,): august -- ['ˈɑɡəst', 'ˈɔɡəst']
"SUGD", # (SUGD,): suggested -- ['səˈdʒɛstɪd']
"SUG/-D", # (SUG, -D): suggested -- ['səˈdʒɛstɪd']
"SAEFD", # (SAEFD,): satisfied -- ['ˈsætəsˌfaɪd', 'ˈsætɪsˌfaɪd']
"SAEF/-D", # (SAEF, -D): satisfied -- ['ˈsætəsˌfaɪd', 'ˈsætɪsˌfaɪd']
"OEPG", # (OEPG,): opening -- ['ˈoʊpənɪŋ']
"AO*PLT", # (AO*MT,): amount -- ['əˈmaʊnt']
"APLT", # (AMT,): amount -- ['əˈmaʊnt']
"A*PLT", # (A*MT,): amount -- ['əˈmaʊnt']
"TPHAPBL", # (NANL,): animal -- ['ˈænəməɫ']
"PHAPBL", # (MANL,): animal -- ['ˈænəməɫ']
"PHA*PBL", # (MA*NL,): animal -- ['ˈænəməɫ']
"SEP", # (SEP,): accept -- ['ækˈsɛpt', 'əkˈsɛpt']
"PH*ERB", # (ME*ʃ,): measure -- ['ˈmɛʒɝ']
"HROGT", # (LOGT,): altogether -- ['ˌɔɫtəˈɡɛðɝ']
"TPHO*EUR", # (NOI*R,): narrow -- ['ˈnæɹoʊ', 'ˈnɛɹoʊ']
"SHREURPL", # (SLIRM,): similar -- ['ˈsɪməɫɝ']
"SHRAR", # (SLAR,): similar -- ['ˈsɪməɫɝ']
"SEUPL", # (SIM,): similar -- ['ˈsɪməɫɝ']
"KWRE", # (YE,): yes -- ['ˈjɛs']
"ELG", # (ELG,): exactly -- ['ɪɡˈzæktɫi']
"K-FD", # (K-FD,): confidence -- ['ˈkɑnfədəns']
"PHO*ED", # (MOE*D,): method -- ['ˈmɛθəd']
"PHO*D", # (MO*D,): method -- ['ˈmɛθəd']
"S-PBLT", # (S-NLT,): isn't -- ['ˈɪzən', 'ˈɪzənt', 'ɪzənt']
"S-PBT", # (S-NT,): isn't -- ['ˈɪzən', 'ˈɪzənt', 'ɪzənt']
"KR", # (KR,): consider -- ['kənˈsɪdɝ']
"S*EPD", # (SE*PD,): accepted -- ['ækˈsɛptɪd', 'əkˈsɛptɪd']
"SEPD", # (SEPD,): accepted -- ['ækˈsɛptɪd', 'əkˈsɛptɪd']
"KW", # (KW,): request -- ['ɹiˈkwɛst', 'ɹɪˈkwɛst']
"PRAF", # (PRAF,): paragraph -- ['ˈpæɹəˌɡɹæf', 'ˈpɛɹəˌɡɹæf']
"PRA*F", # (PRA*F,): paragraph -- ['ˈpæɹəˌɡɹæf', 'ˈpɛɹəˌɡɹæf']
"WUFL", # (WUFL,): wonderful -- ['ˈwəndɝfəɫ']
"KP-PL", # (X-M,): example -- ['ɪɡˈzæmpəɫ']
"TKREU", # (DRI,): drink -- ['ˈdɹɪŋk']
"ORDZ", # (ORDZ,): orders -- ['ˈɔɹdɝz']
"TKEG", # (DEG,): degree -- ['dɪˈɡɹi']
"PROU", # (PROU,): produce -- ['ˈpɹoʊdus', 'pɹəˈdus']
"PRO*UD", # (PROU*D,): produced -- ['pɹəˈdust']
"ORPBLG", # (ORJ,): original -- ['ɝˈɪdʒənəɫ']
"OERPBLG", # (OERJ,): original -- ['ɝˈɪdʒənəɫ']
"TKPWA*RPB", # (GA*RN,): garden -- ['ˈɡɑɹdən']
"TKPWEUPB", # (GIN,): begin -- ['bɪˈɡɪn']
"A*FPB", # (A*FN,): afternoon -- ['ˌæftɝˈnun']
"SPOR", # (SPOR,): support -- ['səˈpɔɹt']
"WREUG", # (WRIG,): writing -- ['ˈɹaɪtɪŋ']
"SPEBGT", # (SPEKT,): respect -- ['ɹiˈspɛkt', 'ɹɪˈspɛkt']
"RAEUPL", # (RAIM,): remain -- ['ɹiˈmeɪn', 'ɹɪˈmeɪn']
"SOEUT", # (SOIT,): society -- ['səˈsaɪəti']
"SOET", # (SOET,): society -- ['səˈsaɪəti']
"RULT", # (RULT,): result -- ['ɹiˈzəɫt', 'ɹɪˈzəɫt']
"RARD", # (RARD,): regard -- ['ɹɪˈɡɑɹd']
"S*EUPL", # (SI*M,): simple -- ['ˈsɪmpəɫ']
"TPEUG", # (FIG,): figure -- ['ˈfɪɡjɝ']
"TPRORPL", # (FRORM,): former -- ['ˈfɔɹmɝ']
"TPROERPL", # (FROERM,): former -- ['ˈfɔɹmɝ']
"WEPBS", # (WENS,): influence -- ['ˈɪnfɫuəns']
"WREU", # (WRI,): write -- ['ˈɹaɪt']
"TPH-LS", # (N-LS,): unless -- ['ənˈɫɛs']
"PWROEPB", # (BROEN,): broken -- ['ˈbɹoʊkən']
"TPHAEPL", # (NAEM,): enemy -- ['ˈɛnəmi']
"PROEBL", # (PROEBL,): probably -- ['ˈpɹɑbəˌbɫi', 'ˈpɹɑbɫi']
"PROBL", # (PROBL,): probably -- ['ˈpɹɑbəˌbɫi', 'ˈpɹɑbɫi']
"PRO*BL", # (PRO*BL,): probably -- ['ˈpɹɑbəˌbɫi', 'ˈpɹɑbɫi']
"PORPBT", # (PORNT,): important -- ['ˌɪmˈpɔɹtənt']
"PORPB", # (PORN,): important -- ['ˌɪmˈpɔɹtənt']
"RER", # (RER,): remember -- ['ɹiˈmɛmbɝ', 'ɹɪˈmɛmbɝ']
"HUS", # (HUS,): husband -- ['ˈhəzbənd']
"KO*EP", # (KOE*P,): copy -- ['ˈkɑpi']
"KWROPBD", # (YOND,): beyond -- ['ˌbiˈɔnd', 'bɪˈɑnd', 'bɪˈɔnd']
"SOUT", # (SOUT,): south -- ['ˈsaʊθ']
"TAEUG", # (TAIG,): taking -- ['ˈteɪkɪŋ']
"HAEP", # (HAEP,): happy -- ['ˈhæpi']
"PURP", # (PURP,): purpose -- ['ˈpɝpəs']
"TPURT", # (FURT,): further -- ['ˈfɝðɝ']
"TP*URT", # (FU*RT,): further -- ['ˈfɝðɝ']
"KWRAOEU", # (YII,): eye -- ['ˈaɪ']
"T-PBD", # (T-ND,): continued -- ['kənˈtɪnjud']
"KWR-D", # (Y-D,): idea -- ['aɪˈdiə']
"K-PBT", # (K-NT,): can't -- ['ˈkænt']
"WR*EUPB", # (WRI*N,): written -- ['ˈɹɪtən']
"KARBG", # (KAʃG,): character -- ['ˈkɛɹɪktɝ']
"TPOLD", # (FOLD,): followed -- ['ˈfɑɫoʊd']
"ARPBD", # (ARND,): around -- ['ɝˈaʊn', 'ɝˈaʊnd']
"PHAEUG", # (MAIG,): making -- ['ˈmeɪkɪŋ']
"URPBD", # (URND,): understand -- ['ˌəndɝˈstænd']
"AEPBS", # (AENS,): answer -- ['ˈænsɝ']
"RURPBD", # (RURND,): returned -- ['ɹiˈtɝnd', 'ɹɪˈtɝnd']
"RURPB/-D", # (RURN, -D): returned -- ['ɹiˈtɝnd', 'ɹɪˈtɝnd']
"PWREU", # (BRI,): bring -- ['ˈbɹɪŋ']
"TPOLG", # (FOLG,): following -- ['ˈfɑɫoʊɪŋ']
"TPOL/-G", # (FOL, -G): following -- ['ˈfɑɫoʊɪŋ']
"SK", # (SK,): ask -- ['ˈæsk']
"KWE", # (KWE,): question -- ['ˈkwɛstʃən', 'ˈkwɛʃən']
"PWEUS", # (BIS,): business -- ['ˈbɪznəs', 'ˈbɪznɪs']
"PW-Z/-PBS", # (B-Z, -NS): business -- ['ˈbɪznəs', 'ˈbɪznɪs']
"AEPBS/-D", # (AENS, -D): answered -- ['ˈænsɝd']
"WEUPL", # (WIM,): women -- ['ˈwɪmən']
"THR*FR", # (TL*FR,): therefore -- ['ˈðɛɹˌfɔɹ']
"TH-FR", # (TH-FR,): therefore -- ['ˈðɛɹˌfɔɹ']
"TPHURPL", # (NURM,): number -- ['ˈnəmbɝ']
"TPHUPL", # (NUM,): number -- ['ˈnəmbɝ']
"HEP", # (HEP,): help -- ['ˈhɛɫp']
"TPHEUG", # (NIG,): anything -- ['ˈɛniˌθɪŋ']
"ORD", # (ORD,): order -- ['ˈɔɹdɝ']
"PERPB", # (PERN,): person -- ['ˈpɝsən']
"STEU", # (STI,): city -- ['ˈsɪti']
"PWO*ED", # (BOE*D,): body -- ['ˈbɑdi']
"OEP", # (OEP,): open -- ['ˈoʊpən']
"HREF", # (LEF,): leave -- ['ˈɫiv']
"POB", # (POB,): possible -- ['ˈpɑsəbəɫ']
"PO*B", # (PO*B,): possible -- ['ˈpɑsəbəɫ']
"WHR", # (WL,): whether -- ['ˈhwɛðɝ', 'ˈwɛðɝ']
"R-PB", # (R-N,): reason -- ['ˈɹizən']
"KWR", # (Y,): why -- ['ˈhwaɪ', 'ˈwaɪ']
"PW-BG", # (B-K,): become -- ['bɪˈkəm']
"HRAOG", # (LAOG,): looking -- ['ˈɫʊkɪŋ']
"KO*G", # (KO*G,): coming -- ['ˈkəmɪŋ']
"TPHES", # (NES,): necessary -- ['ˈnɛsəˌsɛɹi']
"TR", # (TR,): interest -- ['ˈɪntɝəst', 'ˈɪntɝɪst', 'ˈɪntɹəst', 'ˈɪntɹɪst']
"T-R", # (T-R,): interest -- ['ˈɪntɝəst', 'ˈɪntɝɪst', 'ˈɪntɹəst', 'ˈɪntɹɪst']
"K-T", # (K-T,): account -- ['əˈkaʊnt']
"A/K-T", # (A, K-T): account -- ['əˈkaʊnt']
"PAERT", # (PAERT,): party -- ['ˈpɑɹti']
"R*ED", # (RE*D,): ready -- ['ˈɹɛdi']
"R-D", # (R-D,): ready -- ['ˈɹɛdi']
"RURPB/-G", # (RURN, -G): returning -- ['ɹiˈtɝnɪŋ', 'ɹɪˈtɝnɪŋ']
"REPT/-D", # (REPT, -D): represented -- ['ˌɹɛpɹɪˈzɛntɪd']
"K-RBS", # (K-ʃS,): conscious -- ['ˈkɑnʃəs']
"SR-PBT", # (V-NT,): haven't -- ['ˈhævən', 'ˈhævənt']
"TPEUG/-S", # (FIG, -S): figures -- ['ˈfɪɡjɝz']
"TPH-RPBLG", # (N-RJ,): energy -- ['ˈɛnɝdʒi']
"TPH-RG", # (N-RG,): energy -- ['ˈɛnɝdʒi']
"T-PB", # (T-N,): continue -- ['kənˈtɪnju']
"R-PBS", # (R-NS,): reasons -- ['ˈɹizənz']
"K-RPBD", # (K-RND,): concerned -- ['kənˈsɝnd']
"PAERT/-S", # (PAERT, -S): parties -- ['ˈpɑɹtiz']
"TPH-FD", # (N-FD,): informed -- ['ˌɪnˈfɔɹmd']
"HR-BG", # (L-K,): welcome -- ['ˈwɛɫkəm']
"TPH-DZ", # (N-DZ,): inside -- ['ˈɪnˌsaɪd', 'ˌɪnˈsaɪd']
"PW-Z", # (B-Z,): busy -- ['ˈbɪzi']
"A/K-PD", # (A, K-PD): accompanied -- ['əˈkəmpənid']
"K-RGS", # (K-Rʃn,): consideration -- ['kənˌsɪdɝˈeɪʃən']
"PH-PB", # (M-N,): machine -- ['məˈʃin']
"K-R/RAEUGS", # (K-R, RAIʃn): consideration -- ['kənˌsɪdɝˈeɪʃən']
"STPH-PBS", # (SN-NS,): sentence -- ['ˈsɛntəns']
"PW-BGS", # (B-KS,): becomes -- ['bɪˈkəmz']
"HR-G", # (L-G,): willing -- ['ˈwɪɫɪŋ']
"-LG", # (-LG,): willing -- ['ˈwɪɫɪŋ']
"S-PB", # (S-N,): season -- ['ˈsizən']
"OEP/-G", # (OEP, -G): opening -- ['ˈoʊpənɪŋ']
"K-FRT", # (K-FRT,): comfort -- ['ˈkəmfɝt']
"THR-S", # (TL-S,): there's -- ['ˈðɛɹz']
"K-PBS", # (K-NS,): conditions -- ['kənˈdɪʃənz']
"K-B/-S", # (K-B, -S): conditions -- ['kənˈdɪʃənz']
"PWHR-G", # (BL-G,): building -- ['ˈbɪɫdɪŋ']
"PW-LG", # (B-LG,): building -- ['ˈbɪɫdɪŋ']
"HR-GT", # (L-GT,): altogether -- ['ˌɔɫtəˈɡɛðɝ']
"KERPB/-G", # (KERN, -G): concerning -- ['kənˈsɝnɪŋ']
"K-RPBG", # (K-RNG,): concerning -- ['kənˈsɝnɪŋ']
"TR-G", # (TR-G,): interesting -- ['ˈɪntɝəstɪŋ', 'ˈɪntɝɪstɪŋ', 'ˈɪntɹəstɪŋ', 'ˈɪntɹɪstɪŋ']
"K-F", # (K-F,): confidence -- ['ˈkɑnfədəns']
"PW-DZ", # (B-DZ,): besides -- ['ˌbiˈsaɪdz', 'bɪˈsaɪdz']
"KWR-DZ", # (Y-DZ,): ideas -- ['aɪˈdiəz']
"KWR-D/-S", # (Y-D, -S): ideas -- ['aɪˈdiəz']
"K-R", # (K-R,): consider -- ['kənˈsɪdɝ']
"TKR-BT", # (DR-BT,): distribute -- ['dɪˈstɹɪbjut']
"KP-PT", # (X-PT,): expect -- ['ɪkˈspɛkt']
"PHEPL/-S", # (MEM, -S): members -- ['ˈmɛmbɝz']
"PHEB/-S", # (MEB, -S): members -- ['ˈmɛmbɝz']
"ORD/-D", # (ORD, -D): ordered -- ['ˈɔɹdɝd']
"KWE/-S", # (KWE, -S): questions -- ['ˈkwɛstʃənz']
"TP-RPB", # (F-RN,): fortune -- ['ˈfɔɹtʃən', 'ˈfɔɹtʃun']
"TPH-GS", # (N-ʃn,): nation -- ['ˈneɪʃən']
"PROU/-D", # (PROU, -D): produced -- ['pɹəˈdust']
"PRAOU/-D", # (PRUU, -D): produced -- ['pɹəˈdust']
"ST-PL", # (ST-M,): system -- ['ˈsɪstəm']
"ST-FPL", # (ST-ChL,): system -- ['ˈsɪstəm']
"S-PL", # (S-M,): system -- ['ˈsɪstəm']
"K-PB", # (K-N,): condition -- ['kənˈdɪʃən']
"TK-PBT", # (D-NT,): didn't -- ['ˈdɪdən', 'ˈdɪdənt', 'ˈdɪdnt', 'ˈdɪnt']
"S-FS", # (S-FS,): service -- ['ˈsɝvəs', 'ˈsɝvɪs']
"THR-FR", # (TL-FR,): therefore -- ['ˈðɛɹˌfɔɹ']
"THR-F", # (TL-F,): therefore -- ['ˈðɛɹˌfɔɹ']
"HR-RD", # (L-RD,): already -- ['ɔˈɹɛdi', 'ɔɫˈɹɛdi']
"HR-R", # (L-R,): already -- ['ɔˈɹɛdi', 'ɔɫˈɹɛdi']
"TPH-L", # (N-L,): until -- ['ənˈtɪɫ']
"SR/-G", # (V, -G): having -- ['ˈhævɪŋ']
"SR-G", # (V-G,): having -- ['ˈhævɪŋ']
"HR-PL", # (L-M,): almost -- ['ˈɔɫˌmoʊst']
"ST-G", # (ST-G,): something -- ['ˈsəmθɪŋ']
"SPH-G", # (SM-G,): something -- ['ˈsəmθɪŋ']
"S-G", # (S-G,): something -- ['ˈsəmθɪŋ']
"HR-S", # (L-S,): also -- ['ˈɔɫsoʊ']
"TPH-PB", # (N-N,): under -- ['ˈəndɝ']
"PW-G", # (B-G,): being -- ['ˈbiɪŋ']
"-BG", # (-K,): being -- ['ˈbiɪŋ']
"-B/-G", # (-B, -G): being -- ['ˈbiɪŋ']
"R-PT", # (R-PT,): respect -- ['ɹiˈspɛkt', 'ɹɪˈspɛkt']
"KP-PTD", # (X-PTD,): expected -- ['ɪkˈspɛktəd', 'ɪkˈspɛktɪd']
"TKPW/-S", # (G, -S): goes -- ['ˈɡoʊz']
"TKPW-S", # (G-S,): goes -- ['ˈɡoʊz']
"TPH-TS", # (N-TS,): notice -- ['ˈnoʊtəs', 'ˈnoʊtɪs']
"SRAOUL", # (VUUL,): value -- ['ˈvæɫju']
"SRAO*UL", # (VUU*L,): value -- ['ˈvæɫju']
"P*FR", # (P*FR,): perfect -- ['ˈpɝˌfɪkt', 'pɝˈfɛkt']
"P-FRT", # (P-FRT,): perfect -- ['ˈpɝˌfɪkt', 'pɝˈfɛkt']
"P-FR", # (P-FR,): perfect -- ['ˈpɝˌfɪkt', 'pɝˈfɛkt']
"P-F", # (P-F,): perfect -- ['ˈpɝˌfɪkt', 'pɝˈfɛkt']
"OEBD", # (OEBD,): observed -- ['əbˈzɝvd']
"OEB/-D", # (OEB, -D): observed -- ['əbˈzɝvd']
"KR/-D", # (KR, -D): considered -- ['kənˈsɪdɝd']
"KR-D", # (KR-D,): considered -- ['kənˈsɪdɝd']
"K-R/-D", # (K-R, -D): considered -- ['kənˈsɪdɝd']
"K-FRGS", # (K-FRʃn,): conversation -- ['ˌkɑnvɝˈseɪʃən']
"AFPB", # (AFN,): afternoon -- ['ˌæftɝˈnun']
"K-RBL", # (K-ʃL,): considerable -- ['kənˈsɪdɝəbəɫ']
"K-R/-BL", # (K-R, -BL): considerable -- ['kənˈsɪdɝəbəɫ']
"KR-BL", # (KR-BL,): considerable -- ['kənˈsɪdɝəbəɫ']
"PROR", # (PROR,): proper -- ['ˈpɹɑpɝ']
"SPAOEG", # (SPEEG,): speaking -- ['ˈspikɪŋ']
"TK*G", # (D*G,): doing -- ['ˈduɪŋ']
"OFS", # (OFS,): office -- ['ˈɔfɪs']
"AUFS", # (AUFS,): office -- ['ˈɔfɪs']
"TAEPBGS", # (TAENʃn,): attention -- ['əˈtɛnʃən']
"K-P", # (K-P,): company -- ['ˈkəmpəˌni']
"AG", # (AG,): ago -- ['əˈɡoʊ']
"P-PB", # (P-N,): opinion -- ['əˈpɪnjən']
"WOEUPBD", # (WOIND,): window -- ['ˈwɪndoʊ']
"SEUPBLG", # (SIJ,): single -- ['ˈsɪŋɡəɫ']
"KAER", # (KAER,): carry -- ['ˈkæɹi', 'ˈkɛɹi']
"KHRUG", # (ChRUG,): including -- ['ˌɪnˈkɫudɪŋ']
"KHRUD/-G", # (ChRUD, -G): including -- ['ˌɪnˈkɫudɪŋ']
"KHRU/-G", # (ChRU, -G): including -- ['ˌɪnˈkɫudɪŋ']
"ST-R", # (ST-R,): sister -- ['ˈsɪstɝ']
"PAOERD", # (PEERD,): period -- ['ˈpɪɹiəd']
"EUPL/POB", # (IM, POB): impossible -- ['ˌɪmˈpɑsəbəɫ']
"STPHED", # (SNED,): instead -- ['ˌɪnˈstɛd']
"PWHRU", # (BLU,): blue -- ['ˈbɫu']
"TPA*ER/AES", # (FAE*R, AES): father's -- ['ˈfɑðɝz']
"THOZ", # (THOZ,): those -- ['ˈðoʊz']
"W-R", # (W-R,): where -- ['ˈhwɛɹ', 'ˈwɛɹ']
"AFT", # (AFT,): after -- ['ˈæftɝ']
"AF", # (AF,): after -- ['ˈæftɝ']
"THEZ", # (THEZ,): these -- ['ˈðiz']
"PWOFR", # (BOFR,): before -- ['ˌbiˈfɔɹ', 'bɪˈfɔɹ']
"SPWAO", # (SBAO,): into -- ['ˈɪntu', 'ɪnˈtu', 'ɪntə']
"PW-FR", # (B-FR,): before -- ['ˌbiˈfɔɹ', 'bɪˈfɔɹ']
"TK", # (D,): did -- ['ˈdɪd', 'dɪd']
"SHO", # (SHO,): should -- ['ˈʃʊd']
"-RBD", # (-ʃD,): should -- ['ˈʃʊd']
"K", # (K,): can -- ['ˈkæn', 'kən']
"HREUL", # (LIL,): little -- ['ˈɫɪtəɫ']
"OEPBL", # (OENL,): only -- ['ˈoʊnɫi']
"PW", # (B,): about -- ['əˈbaʊt']
"SRE", # (VE,): very -- ['ˈvɛɹi']
"OER", # (OER,): other -- ['ˈəðɝ']
"KO", # (KO,): could -- ['ˈkʊd']
"WHA", # (WHA,): what -- ['ˈhwət', 'ˈwət']
"KWRAOUR", # (YUUR,): your -- ['ˈjɔɹ', 'ˈjʊɹ']
"TPHEU", # (NI,): any -- ['ˈɛni']
"TPHAO*", # (NAO*,): into -- ['ˈɪntu', 'ɪnˈtu', 'ɪntə']
"TPHAO", # (NAO,): into -- ['ˈɪntu', 'ɪnˈtu', 'ɪntə']
"TP", # (F,): if -- ['ˈɪf', 'ɪf']
"THR", # (TL,): there -- ['ˈðɛɹ']
"TH-R", # (TH-R,): there -- ['ˈðɛɹ']
"HR", # (L,): will -- ['ˈwɪɫ', 'wəɫ']
"WO", # (WO,): would -- ['ˈwʊd']
"R", # (R,): are -- ['ˈɑɹ', 'ɝ']
"-R", # (-R,): are -- ['ˈɑɹ', 'ɝ']
"PHEU", # (MI,): my -- ['ˈmaɪ']
"WR", # (WR,): were -- ['ˈwɝ']
"-RP", # (-RP,): were -- ['ˈwɝ']
"THE", # (THE,): they -- ['ˈðeɪ']
"TH", # (TH,): this -- ['ˈðɪs', 'ðɪs']
"TPR", # (FR,): from -- ['ˈfɹəm']
"SR", # (V,): have -- ['ˈhæv']
"WEU", # (WI,): which -- ['ˈhwɪtʃ', 'ˈwɪtʃ']
"-B", # (-B,): be -- ['ˈbi', 'bi']
"U", # (U,): you -- ['ˈju']
"H", # (H,): had -- ['ˈhæd']
"S", # (S,): is -- ['ˈɪz', 'ɪz']
"W", # (W,): with -- ['ˈwɪð', 'ˈwɪθ', 'wɪð', 'wɪθ']
"T", # (T,): it -- ['ˈɪt', 'ɪt']
"WUZ", # (WUZ,): was -- ['ˈwɑz', 'wəz']
"THA", # (THA,): that -- ['ˈðæt', 'ðət']
"TPH", # (N,): in -- ['ˈɪn', 'ɪn']
"SKP", # (SX,): and -- ['ˈænd', 'ənd']
"-F", # (-F,): of -- ['ˈəv']
		}
plover_ortho_briefs={
"EU",
"TPOUR", # (FOUR,): four -- ['ˈfɔɹ']
"WAR", # (WAR,): war -- ['ˈwɔɹ']
"HOUR", # (HOUR,): hour -- ['ˈaʊɝ', 'ˈaʊɹ']
"OLD", # (OLD,): old -- ['ˈoʊɫd']
"TWO", # (TWO,): two -- ['ˈtu']
"SHOULD", # (SHOULD,): should -- ['ˈʃʊd']
"KOULD", # (KOULD,): could -- ['ˈkʊd']
"KWROUR", # (YOUR,): your -- ['ˈjɔɹ', 'ˈjʊɹ']
"TKO", # (DO,): do -- ['ˈdu']
"TPHO", # (NO,): no -- ['ˈnoʊ']
"WOULD", # (WOULD,): would -- ['ˈwʊd']
"WHO", # (WHO,): who -- ['ˈhu']
"WE", # (WE,): we -- ['ˈwi']
"SO", # (SO,): so -- ['ˈsoʊ']
"PHE", # (ME,): me -- ['ˈmi']
"SHE", # (SHE,): she -- ['ˈʃi']
"PWEU", # (BI,): by -- ['ˈbaɪ']
"HE", # (HE,): he -- ['ˈhi']
		}
plover_misstrokes={
"PR-FPLD", # !! (PR-ChLD,): purchased -- ['pəɹtʃəst']
"PR-FPDZ", # !! (PR-ChDZ,): purchased -- ['pəɹtʃəst']
"OE/-D/-D", # !! (OE, -D, -D): owed -- ['oʊd']
"TPHOFR", # !! (NOFR,): forever -- ['fəɹɛvəɹ']
"RA*EUFPBG", # !! (RAI*FNG,): reign -- ['ɹeɪn']
"EUPB/SREUFD", # !! (IN, VIFD): involved -- ['ɪnvɑɫvd']
"TWOEFL", # !! (TWOEFL,): twelve -- ['twɛɫv']
"EUPB/RAEUR/PWHREU", # !! (IN, RAIR, BLI): invariably -- ['ˌɪnˈvɛɹiəbɫi']
"SPEURBL/HREU", # !! (SPIʃL, LI): specially -- ['ˈspɛʃəɫi', 'ˈspɛʃɫi']
"R-PBGS", # !! (R-Nʃn,): reasoning -- ['ˈɹizənɪŋ']
"AEUR/TKWRA", # !! (AIR, DWRA): area -- ['ˈɛɹiə']
"PWAOEUB/REU", # !! (BIIB, RI): library -- ['ˈɫaɪbɹɛˌɹi']
"SPAEURT/WAL", # !! (SPAIRT, WAL): spiritual -- ['ˈspɪɹɪˌtʃuəɫ']
"ORG/*PLT", # !! (ORG, *MT): argument -- ['ˈɑɹɡjəmənt']
"KOBG/PAOEU/-D", # !! (KOK, PII, -D): occupied -- ['ˈɑkjəˌpaɪd']
"HAPBD/SHAEUBGS", # (HAND, SHAIKS): hand -- ['ˈhænd']
"KAUPB/STAPT", # (KAUN, STAPT): constant -- ['ˈkɑnstənt']
"KAUPB/STRAPBT", # (KAUN, STRANT): constant -- ['ˈkɑnstənt']
"POL/SEU/SEU", # (POL, SI, SI): policy -- ['ˈpɑɫəsi']
"TKUPBL", # (DUNL,): double -- ['ˈdəbəɫ']
"HAOE/TEL", # (HEE, TEL): hotel -- ['hoʊˈtɛɫ']
"STEUPL/PHREU", # (STIM, PLI): simply -- ['ˈsɪmpɫi']
"SKETS", # (SKETS,): success -- ['səkˈsɛs']
"TPWAOEPB", # (FWEEN,): between -- ['bitˈwin', 'bɪtˈwin']
"HARLT", # (HARLT,): heart -- ['ˈhɑɹt']
"RULTSZ", # (RULTSZ,): results -- ['ɹiˈzəɫts', 'ɹɪˈzəɫts']
"PRAOEUP", # (PRIIP,): prepare -- ['pɹiˈpɛɹ']
"TPR-D", # (FR-D,): interested -- ['ˈɪntɝəstəd', 'ˈɪntɝɪstɪd', 'ˈɪntɹəstɪd', 'ˈɪntɹɪstɪd']
"A/TOEPLT", # (A, TOEMT): attempt -- ['əˈtɛmpt']
"PWRAOEPD", # (BREEPD,): prepared -- ['pɹiˈpɛɹd']
"A/STKPWRAOEPLT", # (A, SGREEMT): agreement -- ['əˈɡɹimənt']
"A/A/TKPWRAOEPLT", # (A, A, GREEMT): agreement -- ['əˈɡɹimənt']
"REFD/-D", # (REFD, -D): recognized -- ['ˈɹɛkəɡˌnaɪzd']
"SAULTD", # (SAULTD,): salt -- ['ˈsɔɫt']
"STAULT", # (STAULT,): salt -- ['ˈsɔɫt']
"STOBLG", # (STOBLG,): stock -- ['ˈstɑk']
"KAOPL/KAOL", # (KAOM, KAOL): cool -- ['ˈkuɫ']
"HREULT/RAER", # (LILT, RAER): literary -- ['ˈɫɪtɝˌɛɹi']
"A/TPART", # (A, FART): apart -- ['əˈpɑɹt']
"SRUFT/OPL", # (VUFT, OM): custom -- ['ˈkəstəm']
"SRA/SRAOEUT", # (VA, VIIT): variety -- ['vɝˈaɪəti']
"TPHOETSZ", # (NOETSZ,): notes -- ['ˈnoʊts']
"A/A/PHRAOEU", # (A, A, PLII): apply -- ['əˈpɫaɪ']
"STKOBG", # (SDOK,): stock -- ['ˈstɑk']
"SKWREPBLT/HREU", # (JENLT, LI): gently -- ['ˈdʒɛntɫi']
"HRAEURB", # (LAIʃ,): labor -- ['ˈɫeɪbɝ']
"TEURPL", # (TIRM,): term -- ['ˈtɝm']
"PWREUFPB", # (BRIFN,): prison -- ['ˈpɹɪzən']
"TKWUFT", # (DWUFT,): dust -- ['ˈdəst']
"TKPHRAOELT", # (DPLEELT,): completely -- ['kəmˈpɫitɫi']
"TKPREUFPB", # (DPRIFN,): driven -- ['ˈdɹɪvən']
"RA*PBLG", # (RA*J,): rank -- ['ˈɹæŋk']
"EUPB/KRAOES/-D/-D", # (IN, KREES, -D, -D): increased -- ['ˈɪnˌkɹist', 'ˌɪnˈkɹist']
"A/WROEFP", # (A, WROECh): approach -- ['əˈpɹoʊtʃ']
"A/TPROEFP", # (A, FROECh): approach -- ['əˈpɹoʊtʃ']
"A/PROFRP", # (A, PROMp): approach -- ['əˈpɹoʊtʃ']
"A/PROEF", # (A, PROEF): approach -- ['əˈpɹoʊtʃ']
"A/PHROEFP", # (A, PLOECh): approach -- ['əˈpɹoʊtʃ']
"EPB/S/TAOEUR", # (EN, S, TIIR): entire -- ['ɪnˈtaɪɝ']
"EPB/STAOEUR", # (EN, STIIR): entire -- ['ɪnˈtaɪɝ']
"EPB/TAOEURB", # (EN, TIIʃ): entire -- ['ɪnˈtaɪɝ']
"SUGS/-D", # (SUʃn, -D): suggested -- ['səˈdʒɛstɪd']
"SAEFD/-D", # (SAEFD, -D): satisfied -- ['ˈsætəsˌfaɪd', 'ˈsætɪsˌfaɪd']
"A/A*/A*PLT", # (A, A*, A*MT): amount -- ['əˈmaʊnt']
"PWA*FPBG", # (BA*FNG,): bank -- ['ˈbæŋk']
"STEUPL/HRAR", # (STIM, LAR): similar -- ['ˈsɪməɫɝ']
"A/TARBG", # (A, TAʃG): attack -- ['əˈtæk']
"HR*ELT", # (LE*LT,): health -- ['ˈhɛɫθ']
"EUPB/TAPBT", # (IN, TANT): instant -- ['ˈɪnstənt']
"EUPB/STAPT", # (IN, STAPT): instant -- ['ˈɪnstənt']
"PEUBG/AOUR", # (PIK, UUR): picture -- ['ˈpɪktʃɝ']
"STKWEUPB", # (SDWIN,): begin -- ['bɪˈɡɪn']
"REULT", # (RILT,): result -- ['ɹiˈzəɫt', 'ɹɪˈzəɫt']
"HRERPBD/-D", # (LERND, -D): learned -- ['ˈɫɝnd', 'ˈɫɝnɪd']
"HREUFPG", # (LIChG,): living -- ['ˈɫɪvɪŋ']
"POERPB", # (POERN,): person -- ['ˈpɝsən']
"SREPT/-D", # (VEPT, -D): represented -- ['ˌɹɛpɹɪˈzɛntɪd']
"RUR/KWREU/-D", # (RUR, YI, -D): hurried -- ['ˈhɝid']
"KAUPB/TAEUP/-D", # (KAUN, TAIP, -D): contained -- ['kənˈteɪnd']
"SWR-PBT", # (SWR-NT,): haven't -- ['ˈhævən', 'ˈhævənt']
"SR-PBTD", # (V-NTD,): haven't -- ['ˈhævən', 'ˈhævənt']
"SR-PBLT", # (V-NLT,): haven't -- ['ˈhævən', 'ˈhævənt']
"STOEP/-S", # (STOEP, -S): stones -- ['ˈstoʊnz']
"WASZ/-PBTD", # (WASZ, -NTD): wasn't -- ['ˈwɑzənt', 'ˈwəzənt']
"TRAOET/-D/-D", # (TREET, -D, -D): treated -- ['ˈtɹitɪd']
"TRAOET/#-D", # (TREET, #-D): treated -- ['ˈtɹitɪd']
"WAPBTS/-S", # (WANTS, -S): wants -- ['ˈwɑnts', 'ˈwɔnts']
"WAPBT/-S/-S", # (WANT, -S, -S): wants -- ['ˈwɑnts', 'ˈwɔnts']
"PWREULD/-G", # (BRILD, -G): building -- ['ˈbɪɫdɪŋ']
"PWEULTD/-G", # (BILTD, -G): building -- ['ˈbɪɫdɪŋ']
"PW-DZ/-Z", # (B-DZ, -Z): besides -- ['ˌbiˈsaɪdz', 'bɪˈsaɪdz']
"KWR-TDZ", # (Y-TDZ,): ideas -- ['aɪˈdiəz']
"KWR-PDZ", # (Y-PDZ,): ideas -- ['aɪˈdiəz']
"TKARBG/-PBLS", # (DAʃG, -NLS): darkness -- ['ˈdɑɹknəs']
"SEUTD/-G", # (SITD, -G): sitting -- ['ˈsɪtɪŋ']
"PARTS/-S", # (PARTS, -S): parts -- ['ˈpɑɹts']
"S-FRS", # (S-FRS,): service -- ['ˈsɝvəs', 'ˈsɝvɪs']
"KOFRT", # (KOFRT,): cost -- ['ˈkɑst', 'ˈkɔst']
"PAOERBD", # (PEEʃD,): period -- ['ˈpɪɹiəd']
"PWEULTD", # (BILTD,): built -- ['ˈbɪɫt']
"A/S-P", # (A, S-P): a -- ['ˈeɪ', 'ə']
"SHOUD", # (SHOUD,): should -- ['ˈʃʊd']
"THAEURB", # (THAIʃ,): their -- ['ˈðɛɹ']
"A/UL", # (A, UL): all -- ['ˈɔɫ']
"-T/S-P", # (-T, S-P): the -- ['ˈðə', 'ðə', 'ði']
		}
from typing import Set
plover_ignore: Set[str]=plover_briefs|plover_ortho_briefs|plover_misstrokes
